apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: simulador-do-caos
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simulador-do-caos
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75      
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 80
          periodSeconds: 60
    scaleUp:
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
