name: ci

on:
  workflow_dispatch:

jobs:
  CI:
#    runs-on: ubuntu-22.04
    runs-on: self-hosted
    steps:
      - name: Export variavel
        run: |
          echo "Export variavel:" $GITHUB_RUN_NUMBER
          
      - name: Exibir Variáveis de Ambiente
        run: |
          echo "Variáveis de Ambiente:"
          printenv    
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags:  |
            alexnnascimento/simulador-do-caos:v${{ github.run_number }}
            alexnnascimento/simulador-do-caos:latest


  # CD:
  #   runs-on: ubuntu-latest
  #   needs: [CI]

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     - name: Definindo o contexto
  #       uses: Azure/k8s-set-context@v3.0
  #       with:
  #         method: kubeconfig
  #         kubeconfig: ${{secrets.KUBECONFIG}}
  #     - name: Deploy Kubernetes cluster
  #       uses: Azure/k8s-deploy@v4.9
  #       with:
  #         images: alexnnascimento/simulador-do-caos:v${{ github.run_number }}
  #         force: true
  #         manifests: |
  #           manifests/deploy.yaml
  #           manifests/hpa.yaml
  #           manifests/services.yaml
  #           manifests/ingress.yaml
  #           manifests/clusterissuer.yaml
  #           manifests/certificate.yaml
